apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: booking
    env: dev
  name: demopod
spec:
  containers:
  - image: httpd:latest
    name: demopod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
